# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=1, verbose_name='id')),
                ('password', models.CharField(max_length=1, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='wojiushialbb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=1, verbose_name='id')),
                ('password', models.CharField(max_length=1, verbose_name='password')),
            ],
        ),
    ]
