# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=10, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='wojiushialbb',
            name='userId',
            field=models.CharField(max_length=10, verbose_name='id'),
        ),
    ]
