# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20160826_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=10, verbose_name='username'),
        ),
    ]
