# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20160827_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='null', max_length=10, verbose_name='email'),
        ),
    ]
