# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wojiushialbb',
        ),
    ]
